import { Winery, WineryState } from './types';

export const wineryStates: WineryState[] = [
  {
    name: 'Georgia',
    slug: 'georgia',
    abbreviation: 'GA',
    tagline: 'From Muscadine Roots to Serious Estate Wines',
    overview: 'Let\'s set expectations: Georgia is not Napa. It\'s not Sonoma. If you drive out to North Georgia wine country expecting the same polished tasting rooms and decades-deep cellar programs, you\'re going to be disappointed. But if you show up with an open mind, a sense of adventure, and an appreciation for people who are genuinely passionate about making this work, you\'re going to have a great time. Georgia is home to roughly 44 active wineries, with the vast majority clustered in the North Georgia mountains within a two-hour drive of Atlanta. The state has two recognized AVAs: the Dahlonega Plateau AVA (designated 2018) and the Upper Hiwassee Highlands AVA (shared with North Carolina). The Dahlonega Plateau sits at 1,500+ feet elevation with clay-loam soils that are genuinely well-suited for grape growing. The quality is improving every year. A handful of producers are making wines that earn national medals in blind competitions, and the gap between Georgia and more established regions is narrowing. What Georgia does offer is something unique: picturesque mountain vineyards, live music on the patio, friendly people who are happy to talk about what they\'re growing, and a relaxed atmosphere that makes for a genuinely fun day out. Support the local growers. Their passion and investment today is what builds a real wine region tomorrow. Go out, Drink Boldly, and enjoy the ride.',
    avas: ['Dahlonega Plateau AVA', 'Upper Hiwassee Highlands AVA'],
    keyGrapes: ['Cabernet Franc', 'Cabernet Sauvignon', 'Viognier', 'Petit Manseng', 'Norton', 'Traminette', 'Chambourcin', 'Touriga Nacional', 'Muscadine', 'Malbec', 'Vidal Blanc'],
    wineryCount: 44,
    regions: ['Dahlonega Plateau AVA', 'Ellijay / Jasper / Talking Rock', 'Cleveland / Helen', 'Rabun County', 'Young Harris / Hiawassee / Blairsville', 'East / Central Georgia', 'West Georgia', 'South / Southeast Georgia'],
    keyTakeaways: [
      'Best overall wine quality: Wolf Mountain, Frogtown Cellars, Tiger Mountain, and Stonewall Creek consistently earn the highest marks from serious wine drinkers.',
      'Best total experience: Montaluce (dining), Chateau Elan (resort), Paradise Hills (spa/retreat), Dahlonega Resort (full spa + lodging + restaurant), and Wolf Mountain (upscale wine + food).',
      'Best value: Habersham ($7.50 tastings), Stonewall Creek ($6-10), Cavender Creek ($12-18), and Butterduck (free-$18).',
      'Most family-friendly: Painted Horse (horses, goats, fainting goats), Fainting Goat (goats, dogs), Chateau Meichtry (Clyde the donkey), Kaya (dog/child friendly), Ellijay River (riverside, kid/dog friendly).',
      'Best food: Wolf Mountain (full caf\u00e9 + brunch), Montaluce (farm-to-table restaurant), Tiger Mountain (Red Barn Caf\u00e9).',
      'Closest to Atlanta: Painted Horse (~30 min), Cloudland (~45 min), Big Door Vineyards (~50 min), Chateau Elan (~1 hr).',
    ],
  },
];

export const wineries: Winery[] = [
  // --- DAHLONEGA PLATEAU AVA ---
  {
    slug: 'wolf-mountain-vineyards',
    name: 'Wolf Mountain Vineyards & Winery',
    region: 'Dahlonega Plateau AVA',
    location: '180 Wolf Mountain Trail, Dahlonega, GA',
    grapes: '100% estate: Cabernet Sauvignon, Syrah, Mourvedre, Touriga Nacional (25 acres)',
    sourcing: '100% Estate',
    tastingPrice: '~$20',
    tastingDetails: 'Full tasting experience',
    hours: 'Thu-Sun 11AM-5PM; groups of 8+ need reservations',
    food: 'Full restaurant: Caf\u00e9 (Thu-Sat lunch), Sunday Brunch (reservations required)',
    entertainment: 'Vineyard tours, gourmet dinners, weddings',
    rating: '4.4/5',
    ratingSource: 'TripAdvisor (513 reviews)',
    highlights: ['200+ medals', 'Best-in-Class at San Francisco Chronicle', 'Double Gold at LA International', 'European-style Craftsman cottage winery', 'Blue Ridge Mountain views'],
    description: 'The crown jewel of Georgia wine. First Georgia winery to win Best-in-Class and Double Gold at the San Francisco Chronicle and LA International Wine Competitions. The European-style Craftsman cottage winery sits atop a fieldstone cellar with glass walls overlooking the Blue Ridge Mountains. Travelers compare it favorably to Napa: "We travel a lot to CA and Napa and Wolf Mountain is right up at the top." The pizza at the caf\u00e9 is called "an absolute game changer." Reservations are essential\u2014this place books up.',
    website: 'https://www.wolfmountainvineyards.com',
  },
  {
    slug: 'frogtown-cellars',
    name: 'Frogtown Cellars',
    region: 'Dahlonega Plateau AVA',
    location: '700 Ridge Point Dr, Dahlonega, GA',
    grapes: '100% Georgia estate-grown; 25 varietals including Viognier, Chardonnay, Sangiovese',
    sourcing: '100% Estate',
    tastingPrice: '$10-$15',
    tastingDetails: '6 wines (dry or sweet flight)',
    hours: 'Thu-Sun 12-5PM; 20+ wines available',
    food: 'From-scratch kitchen; special dinners and brunches',
    entertainment: '"Citizen" program lets you help pick and process grapes',
    rating: '3.6/5',
    ratingSource: 'TripAdvisor (363 reviews)',
    highlights: ['500+ medals', 'Featured in Napa Sonoma Magazine', '"French Rules" philosophy\u2014no sugar added', 'All dry wines', 'Viognier and Touch\u00e9 blend standouts'],
    description: 'The serious winemaker of Georgia. 500+ medals in major California competitions alone. The "French Rules" philosophy means completely dry wines that are truly food-friendly. Their "Citizen" program lets you help pick grapes and process them. Reviews are polarized\u2014wine purists love it, but some find the service cold and pricing steep. The Viognier and Touch\u00e9 blend are consistently praised.',
    website: 'https://frogtown.com',
  },
  {
    slug: 'montaluce-winery',
    name: 'Montaluce Winery & Restaurant',
    region: 'Dahlonega Plateau AVA',
    location: '501 Hightower Church Rd, Dahlonega, GA',
    grapes: 'Estate + regional; Pinot Noir, Syrah, Chardonnay, Seyval',
    sourcing: 'Estate + Sourced',
    tastingPrice: '$20-$45/bottle',
    tastingDetails: 'Flights, by the glass, or bottle',
    hours: 'Daily',
    food: 'Full farm-to-table restaurant (lunch/dinner daily, Sunday brunch); 100% scratch, locally-sourced',
    entertainment: 'Wine hikes, wine cellar tours, weddings, events',
    rating: '4.0/5',
    ratingSource: 'TripAdvisor (696 reviews)',
    highlights: ['Tuscan-inspired grand villa estate', 'Farm-to-table restaurant', '"They even make their own ketchup"', 'Most majestic views in Lumpkin County', 'Popular for bachelorette wine hikes'],
    description: 'The Tuscan experience in Georgia. The most majestic views in Lumpkin County from a grand villa estate. Popular for bachelorette wine hikes and weddings. The restaurant uses 100% scratch cooking with local farms. Some find it overpriced for the wine quality, but the overall experience is consistently praised.',
    website: 'https://www.montaluce.com',
  },
  {
    slug: 'three-sisters-vineyards',
    name: 'Three Sisters Vineyards',
    region: 'Dahlonega Plateau AVA',
    location: '439 Vineyard Way, Dahlonega, GA',
    grapes: 'Estate grown on 184 acres; Cab Franc, Merlot, Cab Sauv, Chardonnay, Pinot Noir, Norton',
    sourcing: '100% Estate',
    tastingPrice: '$25',
    tastingDetails: '4-sample flight',
    hours: 'Thu-Sat 11-5, Sun 1-5',
    food: 'Light snacks',
    entertainment: 'Live folk/bluegrass/jazz seasonally on Crush Pad Deck',
    rating: '4.0/5',
    ratingSource: 'TripAdvisor (214 reviews)',
    highlights: ['Dahlonega\'s first farm winery', 'Cherry wood tasting bar', 'Southern folk art and pottery', 'Great Sangiovese and "Fat Boy Red"', 'Reddit wine enthusiasts call it "best overall" in Dahlonega'],
    description: 'Dahlonega\'s first farm winery and the most laid-back in the area. The rock wall patio is "one of the best places to soak in this unique wine region." Great Sangiovese and the popular "Fat Boy Red." Cherry wood tasting bar surrounded by Southern folk art and pottery.',
  },
  {
    slug: 'cavender-creek-vineyard',
    name: 'Cavender Creek Vineyard & Winery',
    region: 'Dahlonega Plateau AVA',
    location: '3610 Cavender Creek Rd, Dahlonega, GA',
    grapes: 'Estate + sourced',
    sourcing: 'Estate + Sourced',
    tastingPrice: '$12-$18',
    tastingDetails: 'Sweet flight $12, Premium $18',
    hours: 'Daily 12:30-6:30PM (later Fri-Sat)',
    food: 'Cheese/snack boards',
    entertainment: 'Cozy cabin atmosphere; community events',
    rating: '4.5/5',
    ratingSource: 'TripAdvisor (196 reviews)',
    highlights: ['Open 7 days a week', 'Owner Claire Livingston is beloved', 'Resident vineyard dog Tucker', 'Cozy cedar-clad cabin interior', '"Captures the true spirit of a North Georgia winery"'],
    description: 'The cozy hidden gem. "Captures what the true spirit of a North Georgia winery should feel like." Owner Claire Livingston is beloved\u2014"a gem and a treat to talk to." Resident vineyard dog Tucker greets everyone. Open 7 days a week, which is unusual for the area.',
  },
  {
    slug: 'kaya-vineyard',
    name: 'Kaya Vineyard & Winery',
    region: 'Dahlonega Plateau AVA',
    location: 'Dahlonega, GA',
    grapes: '100% estate-grown',
    sourcing: '100% Estate',
    tastingPrice: '$25',
    tastingDetails: '5-wine preset flight (7.5 oz total)',
    hours: 'Check website for seasonal hours',
    food: 'Light options available',
    entertainment: 'Expanding into full resort with 22-room hotel, 15 craftsman cottages, and 300-seat event facility',
    rating: '4.3/5',
    ratingSource: 'TripAdvisor (164 reviews)',
    highlights: ['All wines 100% estate-grown', '1,600 feet elevation', '12-foot windows with panoramic views', 'Dog and child friendly', 'Travelers\' Choice 2025'],
    description: 'The panoramic estate. Built atop a ridge at 1,600 feet elevation with 12-foot windows and the most exquisite panoramic views in North Georgia. All wines 100% estate-grown. Expanding into a full resort experience. Dog and child friendly.',
    website: 'https://www.kayavineyards.com',
  },
  // --- ELLIJAY / JASPER / TALKING ROCK ---
  {
    slug: 'engelheim-vineyards',
    name: 'Engelheim Vineyards',
    region: 'Ellijay / Jasper / Talking Rock',
    location: 'Ellijay, GA',
    grapes: '100% estate vine-to-glass; Cab Franc, Petit Manseng, and more',
    sourcing: '100% Estate',
    tastingPrice: '$20',
    tastingDetails: '4 wines',
    hours: 'Check website for hours',
    food: 'Food trucks regularly',
    entertainment: 'Live music every Sat/Sun; Bavarian-style tasting room',
    rating: '4.7/5',
    ratingSource: 'TripAdvisor (175 reviews)',
    highlights: ['2025 Georgia Winery of the Year', 'True vine-to-glass farm winery', 'Doxology red blend won "Best Georgia Wine" 2021', 'Largest tasting room in area', 'Dog and child friendly with coloring books'],
    description: '2025 Georgia Winery of the Year. A true vine-to-glass farm winery. Bavarian-style tasting room (largest in area) with 15-20 wines from dry to sweet. Award winners include Doxology (red blend, "Best Georgia Wine" 2021), Petit Manseng (2020), and Cab Franc.',
    website: 'https://www.engelheim.com',
  },
  {
    slug: 'cartecay-vineyards',
    name: 'Cartecay Vineyards',
    region: 'Ellijay / Jasper / Talking Rock',
    location: 'Ellijay, GA',
    grapes: '100% Cartecay grapes from 14-acre estate property',
    sourcing: '100% Estate',
    tastingPrice: 'Check at visit',
    tastingDetails: 'Various options available',
    hours: 'Check website for hours',
    food: 'Food trucks regularly',
    entertainment: 'Live music every weekend; annual Crush Fest in September',
    rating: '3.8/5',
    ratingSource: 'TripAdvisor',
    highlights: ['Started the North Georgia wine revolution', 'Restored circa-1890 Tasting Barn', 'Traminette and Chimney White are favorites', 'Annual Crush Fest is a can\'t-miss', 'True 100% estate wines'],
    description: 'The pioneer that started the North Georgia wine revolution. 100% of their wines come from 100% Cartecay grapes\u2014true estate wines from a 14-acre property. Their restored circa-1890 Tasting Barn with iconic chimney stack is the centerpiece. Mixed wine reviews but atmosphere is universally loved.',
    website: 'https://cartecayvineyards.com',
  },
  {
    slug: 'chateau-meichtry',
    name: 'Chateau Meichtry Family Vineyard',
    region: 'Ellijay / Jasper / Talking Rock',
    location: 'Talking Rock, GA',
    grapes: 'Estate + sourced',
    sourcing: 'Estate + Sourced',
    tastingPrice: '$14',
    tastingDetails: '5 wines',
    hours: 'Check website for hours',
    food: 'Food trucks on weekends',
    entertainment: 'Live music weekends; manicured gardens; Clyde the donkey',
    rating: '4.7/5',
    ratingSource: 'TripAdvisor (208 reviews)',
    highlights: ['Highest-rated in Ellijay/Jasper area', 'French country-inspired', 'Famous wine in chocolate cups', 'Clyde the donkey', '"Rivals anything in CA"'],
    description: 'French country elegance and the highest-rated winery in the Ellijay/Jasper area. Manicured gardens tended by the owner herself. Kids love Clyde the donkey. Famous for their wine in chocolate cups. California wine lovers say "this place rivals anything in CA."',
  },
  {
    slug: 'fainting-goat-vineyards',
    name: 'Fainting Goat Vineyards',
    region: 'Ellijay / Jasper / Talking Rock',
    location: 'Jasper, GA',
    grapes: 'Certified French vine stock',
    sourcing: 'Estate + Sourced',
    tastingPrice: 'Check at visit',
    tastingDetails: '15+ wines from dry to sweet',
    hours: 'Check website for hours',
    food: 'BYOF welcome',
    entertainment: 'Live music every Sat/Sun (always free); Sunset Concert Series; four fainting goats and Great Pyrenees dogs',
    rating: '4.4/5',
    ratingSource: 'TripAdvisor (142 reviews)',
    highlights: ['Four real fainting goats (Ronnie, Reagan, Dolley, Mamie)', 'Great Pyrenees dogs', '50-foot veranda with panoramic views', '30-foot ceilings inside', 'Free live music every weekend'],
    description: 'Where goats meet grapes. Family-owned boutique on Burnt Mountain with certified French vine stock. Four real fainting goats plus Great Pyrenees dogs welcome visitors. 50-foot veranda with panoramic views and 30-foot ceilings inside. BYOF welcome.',
    website: 'https://www.faintinggoatvineyardsandwinery.com',
  },
  {
    slug: 'ott-farms-vineyard',
    name: 'Ott Farms & Vineyard',
    region: 'Ellijay / Jasper / Talking Rock',
    location: 'Ellijay, GA',
    grapes: '8+ acres: Seyval Blanc, Traminette, Vidal Blanc, Chambourcin, Lenoire, Cab Franc',
    sourcing: '100% Estate',
    tastingPrice: 'Check at visit',
    tastingDetails: 'Various options',
    hours: 'Check website for hours',
    food: 'Food trucks',
    entertainment: 'Live music regularly; open mic nights on Tuesdays',
    rating: '4.5/5',
    ratingSource: 'TripAdvisor (53 reviews)',
    highlights: ['180-degree mountain views', '20 acres with 8+ under vine', 'Owner developed most other vineyards in the area', 'Wines "well balanced, not overly sweet"', 'Open mic Tuesdays'],
    description: 'The view king. 180-degree mountain views on 20 acres with 8+ acres of vines. Owner Michael developed most of the other vineyards in the area. Wines praised as "well balanced, not overly sweet."',
  },
  {
    slug: 'sharp-mountain-vineyards',
    name: 'Sharp Mountain Vineyards',
    region: 'Ellijay / Jasper / Talking Rock',
    location: 'Jasper, GA',
    grapes: 'Cab Franc, Sangiovese, Pinot Gris on 5 acres at 1,600 feet',
    sourcing: '100% Estate',
    tastingPrice: '$20-$30/bottle',
    tastingDetails: 'Small tasting room experience',
    hours: 'Fri-Sun',
    food: 'Pavilion for picnics',
    entertainment: 'Beautiful mountain views; boutique atmosphere',
    rating: '4.5/5',
    ratingSource: 'TripAdvisor',
    highlights: ['Family-owned since 1995', '26-acre estate at 1,600 feet', 'Old-world handcrafted wines', 'Unusual varieties for Georgia', '"Hidden gem in our own backyard"'],
    description: 'The boutique. Family-owned since 1995 on a 26-acre estate (5 acres under vine) at 1,600 feet. Old-world handcrafted wines including Cab Franc, Sangiovese, Pinot Gris\u2014varieties unusual for Georgia. A "hidden gem in our own backyard."',
  },
  // --- CLEVELAND / HELEN ---
  {
    slug: 'yonah-mountain-vineyards',
    name: 'Yonah Mountain Vineyards',
    region: 'Cleveland / Helen',
    location: 'Cleveland, GA',
    grapes: 'Sauvignon Blanc, Chardonnay, Cab Franc, Petit Verdot',
    sourcing: 'Estate + Sourced',
    tastingPrice: '$40-$65',
    tastingDetails: 'Cave tour experience',
    hours: 'Check website for hours',
    food: 'Beer also available',
    entertainment: 'Wine cave tours beneath Yonah Mountain rock face; 10,000 sq ft ballroom for weddings',
    rating: '4.2/5',
    ratingSource: 'TripAdvisor',
    highlights: ['Stunning wine cave tours', 'Dramatic Yonah Mountain rock face backdrop', 'Premium Totem bottling ($100)', 'Owner Bob Miller is "damn proud of what he does"', 'Cab Franc and Genesis 11 are popular'],
    description: 'The cave experience. Stunning wine cave tours beneath dramatic Yonah Mountain rock face. The priciest option in the Cleveland area but the experience is unique. Popular wines: Cab Franc and Genesis 11.',
  },
  {
    slug: 'habersham-winery',
    name: 'Habersham Winery',
    region: 'Cleveland / Helen',
    location: 'Nacoochee Village, near Helen, GA',
    grapes: 'Muscadine, Merlot, Scarlet, and more',
    sourcing: 'Estate + Sourced',
    tastingPrice: '$7.50-$12',
    tastingDetails: '$7.50 for 5 wines, $12 for all wines',
    hours: 'Open daily',
    food: 'Not specified',
    entertainment: 'Wine slushies ("a MUST if you stop here")',
    rating: '4.0/5',
    ratingSource: 'TripAdvisor',
    highlights: ['One of Georgia\'s oldest wineries (est. 1983)', 'Most affordable tastings in the state', 'Legendary wine slushies', 'Great entry point for wine beginners', '15+ wines available'],
    description: 'Georgia\'s Grande Dame. One of Georgia\'s oldest and largest wineries (est. 1983). Located half a mile from Alpine Helen in Nacoochee Village. Known for muscadine wines and legendary wine slushies ("a MUST if you stop here"). Very affordable tastings. Great entry point for wine beginners.',
  },
  {
    slug: 'cottage-vineyard',
    name: 'The Cottage Vineyard & Winery',
    region: 'Cleveland / Helen',
    location: 'Cleveland, GA',
    grapes: '12 wines including Baby Doll Legs ros\u00e9 and Vidal Blanc',
    sourcing: 'Estate + Sourced',
    tastingPrice: '$17',
    tastingDetails: '5 tastings',
    hours: 'Open 7 days a week 11:55AM-6:02PM ("wine time")',
    food: 'BYOF encouraged\u2014even Papa John\'s delivers here',
    entertainment: 'Live music every Saturday (open until 9PM); craft beers available; Sunday "Jeans & Jesus" worship service at 10:30AM',
    rating: '4.6/5',
    ratingSource: 'TripAdvisor (181 reviews)',
    highlights: ['Open 7 days with quirky "wine time" hours', 'BYOF (Bring Your Own Food) welcome', 'Famous Baby Doll Legs ros\u00e9', 'Live music every Saturday', 'Craft beers available too'],
    description: 'The relaxed favorite. Open 7 days a week with uniquely quirky hours (11:55AM-6:02PM; "wine time"). BYOF is allowed and encouraged. 12 wines including the famous Baby Doll Legs ros\u00e9 and excellent Vidal Blanc. Live music every Saturday.',
  },
  // --- RABUN COUNTY ---
  {
    slug: 'tiger-mountain-vineyards',
    name: 'Tiger Mountain Vineyards',
    region: 'Rabun County',
    location: 'Tiger, GA',
    grapes: 'Estate: Cab Franc, Norton, Malbec, Mourvedre, Viognier, Touriga Nacional, Tannat, Petit Manseng',
    sourcing: '100% Estate',
    tastingPrice: 'Check at visit',
    tastingDetails: 'By appointment only (Sat-Sun)',
    hours: 'Sat-Sun, by appointment',
    food: 'Red Barn Caf\u00e9 serves flatbreads, sandwiches, charcuterie',
    entertainment: 'Newly renovated tasting room; The Retreats offer luxury on-site lodging for up to 60 guests',
    rating: '4.4/5',
    ratingSource: 'TripAdvisor (137 reviews)',
    highlights: ['Fifth-generation farm', 'Only 2,500-3,000 cases annually', 'Serious European varietals', 'Red Barn Caf\u00e9', 'Luxury on-site lodging'],
    description: 'The boutique estate. A fifth-generation farm producing only 2,500-3,000 cases annually of estate-grown European varietals. Newly renovated tasting room and barn. The Retreats at Tiger Mountain offer luxury on-site lodging for up to 60 guests. By appointment only.',
  },
  {
    slug: 'stonewall-creek-vineyards',
    name: 'Stonewall Creek Vineyards',
    region: 'Rabun County',
    location: 'Tiger, GA',
    grapes: 'Estate: Malbec, Cab Franc, Cab Sauv, Petit Manseng, Petit Verdot, Tannat',
    sourcing: '100% Estate',
    tastingPrice: '$6-$10',
    tastingDetails: '$6 for 3 wines, $10 for all 6',
    hours: 'Check website for hours',
    food: 'Not specified',
    entertainment: 'Eco-tasting room above vineyards with barrel cave',
    rating: '4.5/5',
    ratingSource: 'TripAdvisor',
    highlights: ['Best tasting value in the state', 'European-style dry wines', 'Cab Franc won "Best Red Wine made by Georgia grapes"', 'Malbec "similar to a French Malbec"', '"Carl and Carla are great hosts with phenomenal wines"'],
    description: 'The European-style craft winery. The Fackler family grows serious varietals in a peaceful valley. Wines are distinctly European-style and dry. Tastings are a bargain. Their Cab Franc won "Best Red Wine made by Georgia grapes" and the Malbec is "similar to a French Malbec." "Carl and Carla are great hosts with absolutely phenomenal wines."',
  },
  {
    slug: '12-spies-vineyards',
    name: '12 Spies Vineyards',
    region: 'Rabun County',
    location: 'Rabun Gap, GA',
    grapes: '10 varietals from sweet to dry',
    sourcing: 'Estate + Sourced',
    tastingPrice: '$12',
    tastingDetails: '4 wines',
    hours: 'Wed-Sun',
    food: 'Picnics welcome; gift shop',
    entertainment: '"Vino Veranda" with mountain and valley views',
    rating: '4.7/5',
    ratingSource: 'TripAdvisor (139 reviews)',
    highlights: ['21+ only property (rare for Georgia)', '9 acres of sloping mountain land', 'Owner Mike is extremely friendly', 'Vino Veranda with mountain views', 'Piece of heaven'],
    description: 'A piece of heaven. A 21+ only property (rare for Georgia) on 9 acres of sloping mountain land. The "Vino Veranda" offers mountain and valley views. Owner Mike is praised as extremely friendly and welcoming.',
    website: 'https://www.12spiesvineyards.com',
  },
  // --- YOUNG HARRIS / HIAWASSEE / BLAIRSVILLE ---
  {
    slug: 'crane-creek-vineyards',
    name: 'Crane Creek Vineyards',
    region: 'Young Harris / Hiawassee / Blairsville',
    location: 'Young Harris, GA',
    grapes: 'Estate + sourced',
    sourcing: 'Estate + Sourced',
    tastingPrice: 'Check at visit',
    tastingDetails: 'Two distinct tasting rooms (Stone House and Farmhouse Market)',
    hours: 'No reservations required',
    food: 'On-site restaurant',
    entertainment: 'Live music on Saturdays; friendly resident dogs (including three-legged Crash)',
    rating: '4.8/5',
    ratingSource: 'TripAdvisor (298 reviews)',
    highlights: ['Highest-rated vineyard on TripAdvisor', 'Near Brasstown Bald (Georgia\'s highest peak)', 'Award-winning Hellbender Red', 'Two distinct tasting rooms', 'Sweeping panoramic views'],
    description: 'The panoramic champion. Highest-rated vineyard on TripAdvisor with sweeping panoramic views near Brasstown Bald (Georgia\'s highest peak). Family-owned with two distinct tasting rooms. The award-winning Hellbender Red is the must-try. Friendly resident dogs including three-legged Crash. No reservations required.',
  },
  {
    slug: 'odom-springs-vineyards',
    name: 'Odom Springs Vineyards',
    region: 'Young Harris / Hiawassee / Blairsville',
    location: 'Blairsville, GA',
    grapes: '100% estate grown',
    sourcing: '100% Estate',
    tastingPrice: 'Check at visit',
    tastingDetails: 'Intimate tasting experience',
    hours: 'Check website for hours',
    food: 'Cheese boards available',
    entertainment: 'Mountain deck views; owners almost always present',
    rating: '4.9/5',
    ratingSource: 'TripAdvisor (109 reviews)',
    highlights: ['Highest TripAdvisor rating in all of Georgia', '100% estate grown', 'Siblings Steve and Shari Odom name wines after family', '"Stunned" California wine enthusiasts', '"The Naughty Red was velvety smooth"'],
    description: 'The people\'s favorite. Highest TripAdvisor rating in all of Georgia at 4.9/5. 100% estate grown. Siblings Steve and Shari Odom name wines after family members. "The Naughty Red was velvety smooth\u2014honestly surprising for a wine from GA. I\'m a California wine enthusiast and was stunned." The owners are almost always present, enriching every visit with personal history.',
  },
  {
    slug: 'hightower-creek-vineyards',
    name: 'Hightower Creek Vineyards',
    region: 'Young Harris / Hiawassee / Blairsville',
    location: 'Hiawassee, GA',
    grapes: 'Estate + sourced: Cab Franc, Pinot Gris, Merlot, Norton, Traminette',
    sourcing: 'Estate + Sourced',
    tastingPrice: 'Check at visit',
    tastingDetails: 'Wine and mead tastings',
    hours: 'Check website for hours',
    food: 'Not specified',
    entertainment: 'Live music Mar-Oct Saturdays plus evening concerts; covered deck with mountain/vineyard/pond views',
    rating: '4.7/5',
    ratingSource: 'TripAdvisor (86 reviews)',
    highlights: ['Both wines AND meads (honey wines)', 'Toasty Knight mead is "ridiculously delicious"', 'Live music season March-October', 'Mountain/vineyard/pond views', 'Unique wine + mead combo'],
    description: 'Wine and mead. Unique for offering both wines and meads (honey wines). The Toasty Knight mead is "ridiculously delicious to sip around a campfire." Live music March through October on Saturdays plus evening concerts. Covered deck with mountain, vineyard, and pond views.',
  },
  {
    slug: 'paradise-hills-winery',
    name: 'Paradise Hills Winery Resort & Spa',
    region: 'Young Harris / Hiawassee / Blairsville',
    location: 'Blairsville, GA',
    grapes: 'Farm winery producing mostly dry wines',
    sourcing: 'Estate + Sourced',
    tastingPrice: 'Check at visit',
    tastingDetails: 'Tasting at resort winery',
    hours: 'Resort hours; check website',
    food: 'Resort dining',
    entertainment: 'Luxury cabin rentals, European-style spa, comedy tours, retreats, live music',
    rating: '4.4/5',
    ratingSource: 'TripAdvisor (236 reviews)',
    highlights: ['42-acre mountain ridge resort', 'Established 1988\u2014one of Georgia\'s oldest', 'Veteran and women-owned', 'European-style spa', 'Resort cabins $150-400/night'],
    description: 'The complete escape. A 42-acre mountain ridge resort combining winery, luxury cabin rentals, and European-style spa. Established in 1988\u2014one of Georgia\'s oldest. Veteran and women-owned. Comedy tours, retreats (Woodsy Woman Weekend, couples retreats, business retreats), and live music.',
    website: 'https://www.paradisehillsga.com',
  },
  // --- EAST / CENTRAL GEORGIA ---
  {
    slug: 'chateau-elan',
    name: 'Chateau Elan Winery & Resort',
    region: 'East / Central Georgia',
    location: 'Braselton, GA (1 hour NE of Atlanta)',
    grapes: 'European varietals',
    sourcing: 'Estate + Sourced',
    tastingPrice: 'Check at visit',
    tastingDetails: '7 generous pours',
    hours: 'Check website for hours',
    food: 'Multiple restaurants: Versailles, Paddy\'s Irish Pub, Marc chophouse, Louis\' House of Bourbon',
    entertainment: 'Championship golf, European spa, pool/grotto, cooking classes, weddings',
    rating: '4.0/5',
    ratingSource: 'TripAdvisor (3,768 reviews)',
    highlights: ['Georgia\'s largest and most famous winery resort', 'Full luxury destination', 'Multiple restaurants and golf', 'Most-reviewed winery in Georgia', 'One hour from Atlanta'],
    description: 'Georgia\'s Grand Dame. The largest and most famous winery resort in the state. A full luxury destination with multiple restaurants, championship golf, European spa, pool/grotto, and cooking classes. With 3,768 TripAdvisor reviews, it\'s the most-reviewed winery in Georgia. Serious wine enthusiasts find the wines average, but as a total experience, it\'s unmatched.',
  },
  {
    slug: 'cloudland-vineyards',
    name: 'Cloudland Vineyards & Winery',
    region: 'East / Central Georgia',
    location: 'Buford, GA (~45 min from Atlanta)',
    grapes: 'Georgia-suitable varietals including Lomanto (hybrid grape)',
    sourcing: '100% Estate',
    tastingPrice: 'Check at visit',
    tastingDetails: 'Various options',
    hours: 'Check website for hours',
    food: 'Food trucks',
    entertainment: 'Live music Fri-Sat; fire pits',
    rating: '4.3/5',
    ratingSource: 'TripAdvisor',
    highlights: ['Philosophy-driven\u2014farming grapes made for the region', 'Won "best red wine from non-European grapes"', 'No sweet wines\u2014all dry', '10 acres at 1,300 ft near Lake Lanier', 'Closest quality winery to Atlanta (~45 min)'],
    description: 'The philosophy winery. A philosophy-driven operation focused on "farming grapes made for our region." Won "best red wine from non-European grapes" for their 2019 Lomanto (a hybrid grape). Founded by Sean Wilborn, who champions Georgia-suitable varietals. No sweet wines\u2014all dry. One of the closest quality wineries to Atlanta.',
  },
  // --- WEST GEORGIA ---
  {
    slug: 'big-door-vineyards',
    name: 'Big Door Vineyards',
    region: 'West Georgia',
    location: 'White, GA (50-60 min from Atlanta)',
    grapes: 'Wines bottled by sister winery Horse Creek',
    sourcing: 'Primarily Sourced',
    tastingPrice: '$14',
    tastingDetails: '4 pours (1.5 oz each)',
    hours: 'Check website for hours',
    food: 'Charcuterie boards and paninis (locally sourced)',
    entertainment: 'Live music weekends; yoga classes and events; pond with waterfall and walking trail',
    rating: '4.8/5',
    ratingSource: 'TripAdvisor (32 reviews)',
    highlights: ['Atlanta\'s closest quality winery', 'Beautiful valley setting', 'Pond with waterfall and walking trail', 'Near-perfect rating', 'Great for date nights'],
    description: 'Atlanta\'s closest quality winery. Only 50-60 minutes from downtown Atlanta in White, GA. Beautiful valley setting with vine-covered hills, a pond with waterfall, and walking trail. Wines bottled by sister winery Horse Creek. Near-perfect TripAdvisor rating. Great for date nights.',
    website: 'https://bigdoorvineyards.com',
  },
  {
    slug: 'little-vine-vineyards',
    name: 'Little Vine Vineyards',
    region: 'West Georgia',
    location: 'Villa Rica, GA',
    grapes: 'Estate: Norton, LeNoir, Blanc du Bois, Villard Blanc, Herbemont',
    sourcing: '100% Estate',
    tastingPrice: 'Check at visit',
    tastingDetails: 'Tasting room experience',
    hours: 'Thu-Sun',
    food: 'Not specified',
    entertainment: 'Historic vineyard with revival story',
    rating: '4.0/5',
    ratingSource: 'TripAdvisor',
    highlights: ['First commercial wine grapes in West Central Georgia since 1907', 'Reviving pre-Prohibition tradition', 'Estate-grown heritage varietals', 'Historic significance'],
    description: 'The historic revival. The first commercial wine grapes planted in West Central Georgia since 1907. Estate-grown Norton, LeNoir, Blanc du Bois, Villard Blanc, and Herbemont. Reviving the tradition of 20,000 acres of vineyards that existed before Prohibition.',
    website: 'https://www.littlevinevineyards.com',
  },
  // --- SOUTH / SOUTHEAST GEORGIA ---
  {
    slug: 'butterduck-estates',
    name: 'Butterduck Estates Winery',
    region: 'South / Southeast Georgia',
    location: 'Guyton, GA (near Savannah)',
    grapes: 'Merlot, Sangiovese, Viognier + fruit wines (blueberry, blackberry, peach)',
    sourcing: 'Estate + Sourced',
    tastingPrice: 'Free-$18',
    tastingDetails: 'Free (3 wines), Deluxe $15 (6 wines), Grand $18 (10 wines)',
    hours: 'Check website for hours',
    food: 'Cheese plates and chocolates',
    entertainment: 'Brodie the wine dog; 20th anniversary 2026',
    rating: '4.7/5',
    ratingSource: 'TripAdvisor (70 reviews)',
    highlights: ['Celebrating 20 years (2006-2026)', 'Near Savannah day trip', 'Both grape and fruit wines', 'Free tasting tier available', '"A hidden jewel"'],
    description: 'The Savannah day trip. Just a short drive from Savannah, celebrating 20 years (2006-2026). Offers both traditional grape wines and fruit wines. Three tasting tiers starting with a free option. Brodie the wine dog. "A hidden jewel."',
    website: 'https://www.butterduckswinery.com',
  },
  {
    slug: 'watermelon-creek-vineyard',
    name: 'Watermelon Creek Vineyard',
    region: 'South / Southeast Georgia',
    location: 'Glennville, GA',
    grapes: 'Heritage (Noble/Carlos muscadine), dry muscadine ros\u00e9, fruit blends',
    sourcing: '100% Estate',
    tastingPrice: '$15',
    tastingDetails: '"Sommelier In Training" tasting experience',
    hours: 'Check website for hours',
    food: 'Full "Winestaurant" with scratch kitchen',
    entertainment: 'Guided tours through 9-generation family property',
    rating: '4.5/5',
    ratingSource: 'TripAdvisor',
    highlights: ['9-generation family property', 'Three wine series: Heritage, Whoopee, Journey', 'Full scratch-kitchen restaurant', 'Guided historical tours', 'A true destination venue'],
    description: 'The heritage destination. A 9-generation family property specializing in muscadine wines. Three wine series: Heritage (Noble/Carlos muscadine), Whoopee (cherry, peach, watermelon blends), and Journey (dry muscadine ros\u00e9). Full "Winestaurant" with scratch kitchen. Proprietor Charles Tillman leads guided tours through the property\'s deep history.',
    website: 'https://www.watermeloncreekvineyard.com',
  },
  // --- ADDITIONAL DAHLONEGA PLATEAU AVA ---
  {
    slug: 'accent-cellars',
    name: 'Accent Cellars',
    region: 'Dahlonega Plateau AVA',
    location: '215 Auraria Rd, Dahlonega, GA',
    grapes: 'Multi-state sourced (GA, CA, WA, TX) + estate Norton; 25+ varieties including Pinot Gris, Chenin Blanc, Roussanne, Gewurztraminer, Chambourcin',
    sourcing: 'Primarily Sourced',
    tastingPrice: '$22-$26',
    tastingDetails: '$22 for 4 wines, $26 for 5; Winemaker\'s Reserve $55/person (reservation only, 3 slots daily)',
    hours: '7 days/week',
    food: 'BYOF encouraged; no on-site kitchen',
    entertainment: 'Live music weekends; games; covered patio + outdoor seating',
    rating: '4.8/5',
    ratingSource: 'TripAdvisor (52 reviews)',
    highlights: ['Education-forward tastings', 'Unusual varietals not found elsewhere in GA', 'Winemaker\'s Reserve experience with Tyler', 'Skin-fermented Blanc du Bois orange wine', 'Reddit-recommended'],
    description: 'Dahlonega\'s education-forward urban winery. Founded by winemaker Tristen Vanhoff, his wife Katie, and brother Tyler Barnes, this micro-winery specializes in unusual varietals you won\'t find elsewhere in Georgia: Gruner Veltliner, skin-fermented Blanc du Bois orange wine, Chenin Blanc, and Roussanne. The $55 Winemaker\'s Reserve Tasting with Tyler is described as a truly unique, personal experience limited to 3 time slots daily. The wine menu spans from bone-dry to dessert styles, with Georgia-grown Chambourcin and muscadine alongside California and Washington fruit. A perfect stop for anyone who wants to learn while they sip.',
    website: 'https://www.accentcellars.com',
  },
  {
    slug: 'dahlonega-resort-vineyard',
    name: 'Dahlonega Resort & Vineyard',
    region: 'Dahlonega Plateau AVA',
    location: 'Dahlonega, GA',
    grapes: 'Estate grown + sourced; "Twisted" wine line',
    sourcing: 'Estate + Sourced',
    tastingPrice: 'Moderate',
    tastingDetails: 'Guided tastings in outdoor Twisted Wine Garden; winery tours; wine release events',
    hours: 'Check website for hours',
    food: 'Full restaurant "Blueberry Hill": breakfast, brunch, lunch, dinner; farm-to-table; locally sourced',
    entertainment: 'Full spa (facials, hot stone massage, aromatherapy); wooded hiking trails; A-frame/cabin/room lodging; weddings & retreats',
    rating: '10/10',
    ratingSource: 'Expedia; 5.0 WeddingWire',
    highlights: ['Featured on NBC TODAY Show', 'Travel + Leisure top winter getaway', 'Full spa resort', 'Chef + winemaker paired experiences', 'A-frame Instagram-worthy lodging'],
    description: 'A full wine-country boutique resort featured by Travel + Leisure and profiled on NBC\'s TODAY Show. The concept is unique: Executive Chef and winemaker work hand in hand to create paired wine-dining experiences. The outdoor Twisted Wine Garden provides tastings under a pavilion. Lodging includes cabins, cozy rooms, and Instagram-worthy A-frames. The spa rounds out the experience. Premium-priced for those wanting it all in one place.',
    website: 'https://www.dahlonegasresort.com',
  },
  // --- ADDITIONAL ELLIJAY / JASPER / TALKING ROCK ---
  {
    slug: 'roo-mountain-vineyards',
    name: 'Roo Mountain Vineyards',
    region: 'Ellijay / Jasper / Talking Rock',
    location: '1497 Old Flat Branch Rd, Ellijay, GA (226 acres)',
    grapes: '100% estate grown (6,000 vines): Cab Sauv, Syrah, Chardonnay, Sauv Blanc, Pinot Grigio, Vidal Blanc, Traminette, Cab Franc',
    sourcing: '100% Estate',
    tastingPrice: '$25-$40/bottle',
    tastingDetails: 'Two tasting rooms; wines kept on tap for freshness',
    hours: 'Wed-Sun',
    food: 'On-site bistro: salads, sandwiches, BBQ sliders, charcuterie',
    entertainment: '"The Nest" rooftop garden patio; outdoor amphitheater (under construction); VIP winery tours; 21+ only; dog-friendly',
    rating: '3.8/5',
    ratingSource: 'TripAdvisor (21 reviews)',
    highlights: ['Best of Georgia 2024 & 2025', 'The Nest rooftop patio with Blue Ridge views', '226-acre estate', '100% estate grown', 'Adults-only atmosphere'],
    description: 'The hottest new arrival in Ellijay and the most divisive. Won Best of Georgia two years running. The star attraction is The Nest, a massive rooftop garden patio overlooking 226 acres of vineyard and Blue Ridge Mountains with a stone fireplace in winter. Wines are kept on tap so every pour is fresh. Critics find wines overpriced at $37+ per bottle. The adults-only policy is popular with couples. The bistro offers real food. Arrive early on weekends as The Nest fills within an hour of opening.',
    website: 'https://roomountainvineyards.com',
  },
  {
    slug: 'buckley-vineyards',
    name: 'Buckley Vineyards',
    region: 'Ellijay / Jasper / Talking Rock',
    location: '708 Henry Evans Rd, Ellijay, GA',
    grapes: 'Estate grown: Cab Sauv, Merlot, red blends, rose, white blends (Riesling-Pinot Gris-Chardonnay), apple wine',
    sourcing: '100% Estate',
    tastingPrice: 'Moderate',
    tastingDetails: 'Chip-based tasting system; regular + premium options',
    hours: '7 days/week 12-6PM (Fri til 8PM)',
    food: 'Food trucks weekends; cheese plates',
    entertainment: 'Live music; "Terrioke" Friday karaoke nights; art exhibits; VIP private tastings in screened cabin overlooking Turkey Creek; lodging available',
    rating: '4.8/5',
    ratingSource: 'TripAdvisor (17 reviews)',
    highlights: ['VIP cabin tasting over Turkey Creek', 'Open 7 days a week', 'Terrioke Friday nights', 'Wines named after family members', 'Tranquil creekside setting'],
    description: 'Kevin and Gay Buckley transformed the old Henry Evans homestead into one of Ellijay\'s best-rated wineries. The Turkey Creek setting provides a tranquil backdrop. The VIP private tasting in a screened cabin directly over a rushing creek is one of the most unique offerings in North Georgia. Reviews praise the reserve reds. Wines named after loved ones add a heartfelt personal touch. Open 7 days a week with karaoke Friday nights and regular live music.',
    website: 'https://www.buckleyvineyards.com',
  },
  {
    slug: 'grapes-and-ladders',
    name: 'Grapes and Ladders Winery',
    region: 'Ellijay / Jasper / Talking Rock',
    location: 'Near downtown Ellijay, GA',
    grapes: 'Estate + California sourced for drier offerings; sweet wines and fruit wines (peach, blueberry, blackberry)',
    sourcing: 'Estate + Sourced',
    tastingPrice: '$15-$25/bottle',
    tastingDetails: 'Walk-ins welcome',
    hours: 'Wed-Sun 12-6PM (Thu til 8PM)',
    food: 'Food trucks select days; cheese boards',
    entertainment: 'Live music every Thursday and Saturday; covered patio; small stage; lawn activities; kid/pet friendly',
    rating: '4.6/5',
    ratingSource: 'TripAdvisor (9 reviews)',
    highlights: ['California grapes for dry wines', 'Something for every palate', 'Live music Thu & Sat', 'Family-owned and operated', 'Quaint alternative to larger wineries'],
    description: 'A smaller gem that catches visitors off guard. They\'ve brought in California grapes to develop a more robust lineup of drier wine offerings alongside sweet fruit wines and slushies. Owner Cindy is praised as a great hostess. If larger wineries feel too crowded or commercial, this quaint spot could be exactly what you\'re looking for. Family-owned and operated with rolling grassy hills and peaceful views.',
    website: undefined,
  },
  {
    slug: 'ellijay-river-vineyards',
    name: 'Ellijay River Vineyards',
    region: 'Ellijay / Jasper / Talking Rock',
    location: '111 River Birch Lane, Ellijay, GA',
    grapes: 'Estate grown; Merlot and other dry wines',
    sourcing: '100% Estate',
    tastingPrice: '$15-$25/bottle',
    tastingDetails: 'Wine by glass/bottle at riverside tent',
    hours: 'Weekends only (Sat-Sun 1-8PM)',
    food: 'Cheese plates and charcuterie; BYOP (bring your own picnic) encouraged',
    entertainment: 'Riverside seating, swings, benches, fire pits; lawn games (cornhole); kid/dog friendly',
    rating: '4.7/5',
    ratingSource: 'Google (73 reviews)',
    highlights: ['Georgia\'s only vineyard directly on a river', 'All-outdoor experience', 'Dry wines focused', 'No pretension, no reservations', 'Kid and dog friendly'],
    description: 'Georgia\'s only vineyard directly on a river. No permanent building; instead, a wine tasting tent sits right on the river\'s edge with picnic tables, Adirondack chairs, swings, and benches along the water. The experience is purely outdoor and perfectly casual. Wines focus on dry varietals, a departure from typical sweet Georgia wine. The anti-winery winery: no pretension, no reservations, just wine by a beautiful river. Weekend-only, so plan accordingly.',
    website: undefined,
  },
  // --- ADDITIONAL CLEVELAND / HELEN ---
  {
    slug: 'tesnatee-river-winery',
    name: 'Tesnatee River Winery & Meadery',
    region: 'Cleveland / Helen',
    location: '172 Lloyds Honey Farm Rd, Cleveland, GA (168 acres)',
    grapes: '100% estate grown; 27 acres of vineyard on 168-acre family farm',
    sourcing: '100% Estate',
    tastingPrice: 'Affordable',
    tastingDetails: 'Wines + meads + honey tasting',
    hours: 'Wed-Sun 12-6PM (5:30 Sun)',
    food: 'Bread and honey sampling; snacks',
    entertainment: 'River walks; honey house visit; meet the bees; vineyard/farm tours; seasonal wine slushies; dog-friendly indoors',
    rating: '4.8/5',
    ratingSource: 'TripAdvisor (5 reviews)',
    highlights: ['Dual winery-meadery', 'Multigenerational family farm', '27 acres estate vineyard', '100% real honey (no fillers)', 'Mead that drinks like wine, not beer'],
    description: 'The rare true dual winery-meadery in Georgia, operating on a multigenerational family farm. Their 27 acres of planted vineyard make this one of the larger estate operations in the region. The honey tasting room lets you sample 100% real honey before moving to wine and mead. The mead drinks like wine, not beer, which converts skeptics. Dog-friendly indoors, which is unusual. A newer operation still building reviews but earning devoted fans with its authentic farm-to-glass story.',
    website: 'https://www.tesnateeriverwinery.com',
  },
  // --- ADDITIONAL EAST / CENTRAL GEORGIA ---
  {
    slug: 'painted-horse-winery',
    name: 'Painted Horse Winery & Vineyards',
    region: 'East / Central Georgia',
    location: '2105 Bethany Way, Milton, GA (30 min from Atlanta)',
    grapes: 'Estate grown; farm-to-glass philosophy',
    sourcing: '100% Estate',
    tastingPrice: 'Moderate to premium',
    tastingDetails: 'Wine Flight Winesdays; Friday Night Tasting Series (wine + chocolate pairings)',
    hours: 'Thu-Sun 1-7/8PM',
    food: 'Daily lunch menu from 12PM: fresh sandwiches, charcuterie; BYOF also welcome',
    entertainment: 'Wine Flight Winesdays, Ladies Night, Friday BBQ & Blues, Picnic in the Vines, live music, floral workshops, farm animals (horses, donkeys, goats, fainting goats)',
    rating: '4.5/5',
    ratingSource: 'TripAdvisor (4 reviews)',
    highlights: ['Georgia\'s first woman-founded farm winery', 'Only 30 minutes from Atlanta', '22-acre working horse farm', 'BBQ & Blues Fridays', 'Farm animals on-site'],
    description: 'Georgia\'s first woman-founded farm winery, built from scratch by Pamela Borgel starting in 1991 with her grandfather\'s 1950 Ford 8N tractor. The 22-acre working horse farm in Milton is a massive advantage: it\'s the closest quality winery to Atlanta at just 30 minutes. The calendar is packed with creative events. Kids love meeting horses, goats, and the namesake painted horses. The lunch menu with sandwiches among the vines is a nice differentiator.',
    website: 'https://www.thepaintedhorsewinery.com',
  },
  {
    slug: 'boutier-winery',
    name: 'Boutier Winery & Inn',
    region: 'East / Central Georgia',
    location: '4506 Hudson Rivers Church Rd, Danielsville, GA (20 min from Athens)',
    grapes: 'Mostly estate grown (15-acre vineyard)',
    sourcing: '100% Estate',
    tastingPrice: 'Free-$20',
    tastingDetails: 'Free tastings on weekends; event pricing $5-$20',
    hours: 'Fri-Sun 11AM-5PM',
    food: 'Event food (Ladies Night includes food); wine/cheese pairings',
    entertainment: 'Ladies Night (1st Thu, $20: 2 wines + food + line dancing); Line Dance Lessons (last Thu, $5); live bands ($10); Smooth Jazz Sundays; custom wine labels; 4 luxury B&B suites',
    rating: '4.7/5',
    ratingSource: 'TripAdvisor (67 reviews); Travelers\' Choice',
    highlights: ['TripAdvisor Travelers\' Choice', 'Monthly Ladies Night with line dancing', 'Adjacent B&B with luxury suites', 'Custom wine labels for occasions', 'Only quality winery near Athens/UGA'],
    description: 'Owner Victor Boutier is the heart of this operation. What sets Boutier apart is its event programming: the monthly Ladies Night with line dancing has built a loyal following, and they host live bands from rootsy blues-rock to classic Motown. The adjacent B&B has 4 luxury suites with spa bathrooms, making it a full Stay & Sip experience. Custom wine labels for special occasions add a personal touch. Only 20 minutes from Athens, this is the perfect winery for UGA-adjacent visitors.',
    website: 'https://boutierwinery.com',
  },
  {
    slug: 'blue-cielo-farms',
    name: 'Blue Cielo Farms Vineyards & Winery',
    region: 'East / Central Georgia',
    location: 'Elberton, GA (lakeside on Richard B. Russell Lake) + Commerce, GA (185-acre tree farm)',
    grapes: 'Estate grown at both locations: Cabernet, Tannat, Petit Verdot, Chardonnay, Merlot, Blanc du Bois, muscadine, fruit wines',
    sourcing: '100% Estate',
    tastingPrice: '$19-$36/bottle',
    tastingDetails: '$6-17/glass; slushies $7-12',
    hours: 'Check calendar for hours',
    food: 'Catered charcuterie boards via partner',
    entertainment: 'Live music; game nights; wine club dinners in the vines; lakeside setting; special catered events',
    rating: '5.0/5',
    ratingSource: 'WeddingWire',
    highlights: ['Dual Elberton + Commerce locations', 'Lakeside setting on Russell Lake', '185-acre certified tree farm', 'Serious dry reds (Tannat, Cabernet)', 'Wine club dinners in the vines'],
    description: 'A rare find in East Georgia with two distinct locations and a dual identity. The Elberton lakeside venue on Richard B. Russell Lake offers sublime vineyard views. They produce serious dry reds (Tannat at $30, Cabernet at $26) alongside playful sweet muscadines and fruit wines, covering every palate. Wine club members get exclusive dinners in the vines. The Commerce vineyard sits on a 185-acre certified tree farm, reflecting their commitment to sustainability.',
    website: 'https://bluecielofarms.com',
  },
];

// Helper functions
export function getWineryStateBySlug(slug: string): WineryState | undefined {
  return wineryStates.find(s => s.slug === slug);
}

export function getWineriesByState(stateSlug: string): Winery[] {
  const state = getWineryStateBySlug(stateSlug);
  if (!state) return [];
  // For now, all wineries are Georgia. When adding more states, add a stateSlug field to Winery.
  if (stateSlug === 'georgia') return wineries;
  return [];
}

export function getWineryBySlug(slug: string): Winery | undefined {
  return wineries.find(w => w.slug === slug);
}

export function getWineriesGroupedByRegion(stateSlug: string): Record<string, Winery[]> {
  const stateWineries = getWineriesByState(stateSlug);
  const grouped: Record<string, Winery[]> = {};
  for (const w of stateWineries) {
    if (!grouped[w.region]) grouped[w.region] = [];
    grouped[w.region].push(w);
  }
  return grouped;
}

export function getWineriesByRegion(region: string): Winery[] {
  return wineries.filter(w => w.region === region);
}
